version: '3'

services:

  looklook:
    image: violapioggia/chatchat:1.0
    container_name: chatchat1
    ports:
      - "8088:8088"
    environment:
      TZ: Asia/Shanghai
      GOPROXY: https://goproxy.cn,direct
    working_dir: /app
    #volumes:
      #- /etc/localtime:/etc/localtime:ro
      #- /etc/timezone:/etc/timezone:ro
    privileged: true
    restart: always
